jwt:
  secret: lkfasdjflkasjdlfasikfjlasdkfjaslfkajsdsalfdkjasdlfkjgdfsgsfdgsdfgsdfgsdfgsdfgsdfgsdfgsfdgdsfgsdfgsdgsdfgsdfg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
  jpa:
    hibernate:
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8083